name: conda-build-env
channels:
  - conda-forge
dependencies:
  - python
  - wxpython
  - numpy
  - scipy
  - matplotlib
  - pyopengl
  - conda
  - constructor
  - conda-build
  - git 
  - gitpython
  - requests
  - pillow
  - h5py
  - imageio
