# these are the packages needed to build/upload the GSAS2main conda package
# that contains GSAS-II and its .git directory. Too minimal to run GSAS-II.
name: conda-build-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - conda
  - conda-build
  - constructor
  - git
  - gitpython
  - anaconda-client
