name: Test binaries on Win after Compile w/Meson
description: Test GSAS-II binaries on Windows using gitstrap install

runs:
  using: "composite"
  steps:
      - name: Set up conda  # numpy version is selected by conda
        #uses: conda-incubator/setup-miniconda@v3.0.3
        uses: conda-incubator/setup-miniconda@030178870c779d9e5e1b4e563269f3aa69b04081 # v3.0.3 using hash for security
        with:
          activate-environment: build
          environment-file: compile/conda-build-env-nover.yml
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}

      - name: compile with meson
        id: compile-step
        shell: bash -l {0}
        run: |
          gfortran -v
