# this is used to create the conda environment used to build
# the gsas2pkg conda package (requires conda-build) and upload
# it to anaconda.org (requires anaconda-client).
#
name: conda-build-env
channels:
  - conda-forge
dependencies:
  - anaconda-client
  - conda-build
  - gitpython
  - git
  - requests
