# GitHub Action script to build GSAS-II binaries using the new meson
# build process. This is needed for Python 3.12+.
#

name: Old: Compile GSAS-II with meson

permissions:
  contents: write
  
#on: [workflow_dispatch]
#on: [workflow_dispatch, push]

jobs:

  build:
    name: Compile (py${{ matrix.python-version }}, on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-13, macos-14] 
# N.B. glibc on the ubuntu runners is way too new for use on Redhat systems
# so build that on Redhat for dist as a GH release asset (see tinodi_build.sh)
#        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
#        os: [ubuntu-latest, macos-13, macos-14]
#        os: [ubuntu-latest]
#        os: [macos-14]
#        os: [windows-latest]
#        os: [macos-13]

        python-version: ["3.12", "3.13"]
#        python-version: ["3.13"]

    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GSAS-II sources
        shell: bash -l {0}
        run: |
          git clone --single-branch --branch main --depth 50 https://github.com/AdvancedPhotonSource/GSAS-II.git _gsas2
          #git clone --depth 50 https://github.com/AdvancedPhotonSource/GSAS-II.git _gsas2
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: 12
 
      - name: Set up conda  # numpy version is selected by conda
        #uses: conda-incubator/setup-miniconda@v3.0.3
        uses: conda-incubator/setup-miniconda@030178870c779d9e5e1b4e563269f3aa69b04081 # v3.0.3 using hash for security
        with:
          activate-environment: build
          environment-file: compile/conda-build-env-nover.yml
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}

      - name: Compile MacOS
        if: runner.os == 'macOS'
        uses: ./.github/actions/meson-mac

      - name: Compile Linux
        if: runner.os == 'Linux'
        uses: ./.github/actions/meson-linux

      - name: Compile Windows
        if: runner.os == 'Windows'
        uses: ./.github/actions/meson-windows

      # - name: Show Build notes
      #   shell: bash -l {0}
      #   run: |
      #     echo "#### Showing Build.notes.txt"
      #     cat ./tmp/outfiles/Build.notes.txt

      # if debug needed, create a copy of the build directory
      # - name: Save artifact  # creates zip file with directory contents
      #   if: failure()
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #       path: _gsas2
      #       name: compile
      #       retention-days: 1
