# new GitHub Action to test use of outputs

name: dispatch GSAS-II compile scripts

permissions:
  contents: write
  
on: [workflow_dispatch]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
#        os: [ubuntu-latest, macos-13, macos-14]
#        os: [ubuntu-latest]
#        os: [macos-14]
        os: [windows-latest]
#        os: [macos-13]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile MacOS
        if: runner.os == 'macOS'
        uses: ./.github/actions/compile-mac

      - name: Compile Linux
        if: runner.os == 'Linux'
        uses: ./.github/actions/compile-linux

      - name: Compile Windows
        if: runner.os == 'Windows'
        uses: ./.github/actions/compile-win

