name: Master workflow for meson compile & test
# this passes on the matrix settings to another workflow
# with multiple jobs. Intended to replace compile-all-meson.yml

permissions:
  contents: write

on: [workflow_dispatch]

jobs:
  version-matrix:
    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest, macos-13, macos-14] 
# N.B. glibc on the ubuntu runners is way too new for use on Redhat systems
# so build that on Redhat for dist as a GH release asset (see tinodi_build.sh)
#        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
#        os: [ubuntu-latest, macos-13, macos-14]
#        os: [ubuntu-latest]
#        os: [macos-14]
#        os: [windows-latest]
#        os: [macos-13]

        python-version: ["3.12", "3.13"]
#        python-version: ["3.13"]

    uses: ./.github/workflows/compile_test.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit
    