# Build the gsas2full self installer starting with Linux
#
#conda package on Mac (Intel) & Linux
#
name: build gsas2full

#on: [push, pull_request, workflow_dispatch]   # why build on pull request?
#on: [push, workflow_dispatch]
on: [workflow_dispatch]
# run on all platforms this if any of the following change: 
#    install/gitstrap.py
#    install/g2complete
#    install/g2full

jobs:
  build:
    name: gsas2full build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
#        os: [macos-latest]   # testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up conda  # note that conda-build-env.yml fixes Python & numpy versions (alas)
        #uses: conda-incubator/setup-miniconda@v2
        uses: conda-incubator/setup-miniconda@030178870c779d9e5e1b4e563269f3aa69b04081 # v3.0.3 using hash for security
        with:
          activate-environment: build
          environment-file: install/g2complete/conda-build-env.yml
          miniforge-version: latest

      # get the GSAS-II sources
      - name: Get GSAS-II
        run: |
          git clone --depth 50 https://github.com/AdvancedPhotonSource/GSAS-II.git _gsas2          

      - name: create conda gsas2complete package
        shell: bash -l {0}
        run: |
          cd install
          python setgitversion.py ../_gsas2
          conda build g2complete --output-folder ~/build
          ls -l ~/build
          ls -l ~/build/*/*.tar.*
          constructor g2full
          ls -lt *.sh
          
#      - name: diagnostics
#        shell: bash -l {0}
#        run: |
#          conda info
#          conda list
#      - name: right place for build?
#        shell: bash -l {0}
#        run: |
#          cd install
#          ls -l
#          exit 1



