# this does not do anything other than just checkout the current repo
# and the main GSAS-II repo. It is a test file to see if it can be 
# triggered from another repo
name: test workflow
on:
  workflow_dispatch:   # nice for debugging
  repository_dispatch: # run from Web API
jobs:
  build:
    #name: gsas2pkg build on ${{ matrix.os }}
    #runs-on: ${{ matrix.os }}
    name: test run on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GSAS-II sources
        shell: bash -l {0}
        run: |
          git clone --depth 50 https://github.com/AdvancedPhotonSource/GSAS-II.git _gsas2          
