# new GitHub Action to test use of outputs

name: dispatch GSAS-II compile scripts

permissions:
  contents: write
  
on: [workflow_dispatch]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [macos-14]
#        os: [windows-latest]
#        os: [macos-13]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile MacOS
        uses: ./.github/actions/compile-mac
